# Generated by Django 3.0.4 on 2020-04-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=100, verbose_name='restaurant Name')),
                ('address', models.CharField(max_length=250)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('url', models.URLField(verbose_name='URL')),
                ('vanityURI', models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='Restaurant URI')),
                ('aboutUs', models.TextField(max_length=350, verbose_name='About Us')),
                ('mealCost', models.IntegerField(verbose_name='Meal Cost')),
                ('merchantID', models.CharField(max_length=100, verbose_name='PayPal Merchant ID')),
                ('totalCollected', models.IntegerField(default=0)),
                ('mealsDonated', models.IntegerField(default=0)),
                ('goal', models.IntegerField(default=0, verbose_name='Weekly Meal Goal')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealNumber', models.IntegerField()),
                ('dollarAmount', models.IntegerField()),
                ('date', models.DateField(verbose_name='transaction date')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantUser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=100, verbose_name='facility Name')),
                ('active', models.BooleanField(default=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
    ]
