# Generated by Django 3.0.4 on 2020-04-11 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('aboutUs', models.TextField()),
                ('mealCost', models.IntegerField()),
                ('totalCollected', models.IntegerField()),
                ('mealsDonated', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealNumber', models.IntegerField()),
                ('dollarAmount', models.IntegerField()),
                ('date', models.DateField(verbose_name='transaction date')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
    ]
