# Generated by Django 3.0.4 on 2020-04-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facilityName',
            field=models.CharField(max_length=100, verbose_name='facility Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='aboutUs',
            field=models.TextField(verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='goal',
            field=models.IntegerField(verbose_name='Weekly Meal Goal'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mealCost',
            field=models.IntegerField(verbose_name='Meal Cost'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantName',
            field=models.CharField(max_length=100, verbose_name='restaurant Name'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
