# Generated by Django 3.0.4 on 2020-04-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200414_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='mealsDonated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='totalCollected',
            field=models.IntegerField(default=0),
        ),
    ]
