# Generated by Django 3.0.4 on 2020-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_transaction_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='merchantID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
