# Generated by Django 3.0.4 on 2020-04-21 20:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200421_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
    ]
