# Generated by Django 3.0.4 on 2020-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200414_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='restaurantUser',
            field=models.BooleanField(default=False),
        ),
    ]
