# Generated by Django 3.0.4 on 2020-04-22 01:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200421_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='merchantID',
            field=models.CharField(max_length=100, verbose_name='PayPal Merchant ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
