# Generated by Django 3.0.4 on 2020-04-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200421_2334'),
        ('main', '0006_auto_20200422_0149'),
    ]

    operations = [
    ]
