# Generated by Django 3.0.4 on 2020-04-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20200422_1834'),
        ('main', '0007_merge_20200422_1337'),
    ]

    operations = [
    ]
