# Generated by Django 3.0.4 on 2020-04-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_restaurantuser'),
        ('main', '0003_auto_20200414_2349'),
    ]

    operations = [
    ]
