# Generated by Django 3.0.4 on 2020-04-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20200422_2237'),
        ('main', '0008_merge_20200422_2236'),
    ]

    operations = [
    ]
