# Generated by Django 3.0.4 on 2020-04-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_profile_restaurantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurantUser',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
