# Generated by Django 3.0.4 on 2020-04-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_merge_20200415_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='restaurantUser',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='goal',
            field=models.IntegerField(default=0, verbose_name='Weekly Meal Goal'),
        ),
    ]
